---

- hosts: all
  become: true
  tasks:

  - name: install apache package
    dnf:
      name: httpd
      state: latest
      when: ansible_distribution == "Fedora"

  - name: install apache package
    apt:
      name: httpd
      state: latest
      when: ansible_distribution == "Ubuntu"
